/**
 * Seed script: populates the database with WA golf courses from
 * data/wa_courses_full.json (generated by scripts/download-wa-courses.ts).
 *
 * Run with:
 *   npx prisma db seed
 *   (or: npx tsx prisma/seed.ts)
 *
 * Safe to re-run — uses upsert by name.
 */

import * as fs from "fs";
import * as path from "path";
import * as dotenv from "dotenv";
import { PrismaClient } from "../app/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

dotenv.config({ path: path.resolve(__dirname, "../.env") });

interface ApiHole {
  par: number;
  handicap?: number;
  yardage?: number;
}

interface ApiTee {
  tee_name: string;
  tee_color?: string;
  course_rating: number;
  slope_rating: number;
  par_total: number;
  holes?: ApiHole[];
}

interface ApiCourse {
  id: string;
  club_name: string;
  course_name?: string;
  location?: {
    address?: string;
    city?: string;
    state?: string;
    country?: string;
  };
  tees?: { male?: ApiTee[]; female?: ApiTee[] } | ApiTee[];
}

interface DownloadedCourse {
  waName: string;
  waSuburb: string;
  waCity: string;
  waRegion: string;
  waType: string;
  waNotes: string;
  waAddress?: string;
  waPostcode?: string;
  waPhone?: string;
  apiCourse: ApiCourse | null;
}

function flattenTees(tees: ApiCourse["tees"]): ApiTee[] {
  if (!tees) return [];
  if (Array.isArray(tees)) return tees;
  const tag = (group: ApiTee[], suffix: string) =>
    group.map((t) => ({ ...t, tee_name: `${t.tee_name} (${suffix})` }));
  return [...tag(tees.male ?? [], "Male"), ...tag(tees.female ?? [], "Female")];
}

async function main() {
  const dataPath = path.resolve(__dirname, "../data/wa_courses_full.json");

  if (!fs.existsSync(dataPath)) {
    console.error(
      "Error: data/wa_courses_full.json not found.\n" +
        "Run the download script first:\n" +
        "  npx tsx scripts/download-wa-courses.ts"
    );
    process.exit(1);
  }

  const courses: DownloadedCourse[] = JSON.parse(
    fs.readFileSync(dataPath, "utf-8")
  );

  const adapter = new PrismaPg({
    connectionString: process.env.DATABASE_URL!,
  });
  const prisma = new PrismaClient({ adapter });

  let seeded = 0;
  let skipped = 0;

  for (const entry of courses) {
    const api = entry.apiCourse;

    const courseName = api
      ? (() => {
          const parts = [api.club_name, api.course_name].filter(Boolean) as string[];
          const raw = parts.length === 2 && parts[0].trim().toLowerCase() === parts[1].trim().toLowerCase()
            ? parts[0]
            : parts.join(" — ");
          return raw
            .replace(/\bG C\b/g, 'Golf Club')
            .replace(/\bGc\b/g, 'Golf Club')
            .replace(/\bCc\b/g, 'Country Club');
        })()
      : entry.waName;

    const teeData = api ? flattenTees(api.tees) : [];

    try {
      // Check if already exists
      const existing = await prisma.course.findFirst({
        where: { name: courseName },
      });

      if (existing) {
        skipped++;
        continue;
      }

      await prisma.course.create({
        data: {
          name: courseName,
          address: entry.waAddress ?? api?.location?.address,
          postcode: entry.waPostcode ?? null,
          phone: entry.waPhone ?? null,
          city: api?.location?.city ?? entry.waCity,
          state: api?.location?.state ?? "Western Australia",
          country: api?.location?.country ?? "Australia",
          externalId: api?.id != null ? String(api.id) : null,
          tees: {
            create: teeData.map((tee) => ({
              name: tee.tee_name,
              color: tee.tee_color ?? null,
              rating: tee.course_rating,
              slope: tee.slope_rating,
              par: tee.par_total,
              holes: {
                create: (tee.holes ?? []).map((h, i) => ({
                  number: i + 1,
                  par: h.par,
                  strokeIndex: h.handicap ?? 0,
                  distance: h.yardage != null ? Math.round(h.yardage * 0.9144) : null,
                })),
              },
            })),
          },
        },
      });

      const teeCount = teeData.length;
      console.log(
        `✓ ${courseName}${teeCount > 0 ? ` (${teeCount} tees)` : " (no tees — add manually)"}`
      );
      seeded++;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`✗ Failed: ${courseName} — ${msg}`);
    }
  }

  await prisma.$disconnect();

  console.log(`\n──────────────────────────────────────`);
  console.log(`Seeded: ${seeded}  |  Skipped (already exist): ${skipped}`);
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
