/**
 * Seed script: populates the database with WA golf courses from
 * data/wa_courses_full.json (generated by scripts/download-wa-courses.ts).
 *
 * Run with:
 *   npx prisma db seed
 *   (or: npx tsx prisma/seed.ts)
 *
 * Safe to re-run — upserts by externalId (course), [courseId, name] (tee),
 * and [teeId, number] (hole). Will update stale data on subsequent runs.
 */

import * as fs from "fs";
import * as path from "path";
import * as dotenv from "dotenv";
import { PrismaClient } from "../app/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

dotenv.config({ path: path.resolve(__dirname, "../.env") });

interface ApiHole {
  par: number;
  handicap?: number;
  meters?: number;
}

interface ApiTee {
  tee_name: string;
  tee_color?: string;
  course_rating: number;
  slope_rating: number;
  par_total: number;
  holes?: ApiHole[];
}

interface CourseEntry {
  id: number;
  name: string;
  suburb: string;
  city: string;
  region: string;
  state: string;
  country: string;
  type: string;
  address?: string;
  postcode?: string;
  phone?: string;
  latitude?: number;
  longitude?: number;
  notes?: string;
  tees?: ApiTee[];
}

function flattenTees(tees: ApiTee[] | undefined): ApiTee[] {
  if (!tees) return [];

  // Deduplicate by tee name: keep the entry with the highest course_rating
  const best = new Map<string, ApiTee>();
  for (const t of tees) {
    const key = t.tee_name.toLowerCase();
    if (!best.has(key) || t.course_rating > best.get(key)!.course_rating) {
      best.set(key, t);
    }
  }
  return [...best.values()];
}

async function main() {
  const dataPath = path.resolve(__dirname, "../data/wa_courses_full.json");

  if (!fs.existsSync(dataPath)) {
    console.error(
      "Error: data/wa_courses_full.json not found.\n" +
        "Run the download script first:\n" +
        "  npx tsx scripts/download-wa-courses.ts"
    );
    process.exit(1);
  }

  const courses: CourseEntry[] = JSON.parse(
    fs.readFileSync(dataPath, "utf-8")
  );

  const adapter = new PrismaPg({
    connectionString: process.env.DATABASE_URL!,
  });
  const prisma = new PrismaClient({ adapter });

  let inserted = 0;
  let updated = 0;

  for (const entry of courses) {
    const courseName = entry.name;
    const externalId = String(entry.id);
    const teeData = flattenTees(entry.tees);

    try {
      const courseFields = {
        name: courseName,
        address: entry.address ?? null,
        postcode: entry.postcode ?? null,
        phone: entry.phone ?? null,
        suburb: entry.suburb ?? null,
        city: entry.city,
        state: entry.state ?? "Western Australia",
        country: entry.country ?? "Australia",
        region: entry.region ?? null,
        type: entry.type ?? null,
        latitude: entry.latitude ?? null,
        longitude: entry.longitude ?? null,
        notes: entry.notes ?? null,
      };

      // Upsert course by externalId
      const course = await prisma.course.upsert({
        where: { externalId },
        create: { ...courseFields, externalId },
        update: courseFields,
      });

      const isNew = course.createdAt.getTime() > Date.now() - 5000;

      // Upsert tees
      for (const tee of teeData) {
        const upsertedTee = await prisma.tee.upsert({
          where: { courseId_name: { courseId: course.id, name: tee.tee_name } },
          create: {
            courseId: course.id,
            name: tee.tee_name,
            color: tee.tee_color ?? null,
            rating: tee.course_rating,
            slope: tee.slope_rating,
            par: tee.par_total,
          },
          update: {
            color: tee.tee_color ?? null,
            rating: tee.course_rating,
            slope: tee.slope_rating,
            par: tee.par_total,
          },
        });

        // Upsert holes
        for (let i = 0; i < (tee.holes ?? []).length; i++) {
          const h = tee.holes![i];
          await prisma.hole.upsert({
            where: { teeId_number: { teeId: upsertedTee.id, number: i + 1 } },
            create: {
              teeId: upsertedTee.id,
              number: i + 1,
              par: h.par,
              strokeIndex: h.handicap ?? 0,
              distance: h.meters ?? null,
            },
            update: {
              par: h.par,
              strokeIndex: h.handicap ?? 0,
              distance: h.meters ?? null,
            },
          });
        }
      }

      const teeCount = teeData.length;
      if (isNew) {
        console.log(
          `✓ [NEW] ${courseName}${teeCount > 0 ? ` (${teeCount} tees)` : " (no tees — add manually)"}`
        );
        inserted++;
      } else {
        console.log(
          `↻ [UPD] ${courseName}${teeCount > 0 ? ` (${teeCount} tees)` : " (no tees)"}`
        );
        updated++;
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`✗ Failed: ${courseName} — ${msg}`);
    }
  }

  await prisma.$disconnect();

  console.log(`\n──────────────────────────────────────`);
  console.log(`Inserted: ${inserted}  |  Updated: ${updated}  |  Total: ${inserted + updated}`);
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
